### ISSUE TITLE
ICS files cannot be opened on iOS

### ISSUE THREAD

**Issue by amandasystems** [lowercasename/gathio#132]
iOS will save the ICS calendar event as a text file (and, in fact, add .txt to the file name). I tried to figure out which MIME type it is served as, but it seems to be served by some sort of JavaScript action.

I plan on looking into addressing this issue myself unless it's a WONTFIX for some reason.

**Comment by amandasystems** [comment]
Hm, when I look at what it's served as in the Network inspector, I see: `content-type: text/html; charset=utf-8`.

Maybe this is a server thing?

**Comment by lowercasename** [comment]
If you don't work this out, let me know what I can do to help! I don't have an iOS device, but can probably fix something!

**Comment by amandasystems** [comment]
Ok, it's too much work to set up Docker to test this; I got complaints from the mail infrastructure and whatnot.

I'm almost certain the fix is: in `src/routes/frontend`, line 552, add the following line: `res.set("Content-Type", "text/calendar");`.

**Comment by lowercasename** [comment]
Great catch, thank you so much - this has been fixed!

**Comment by amandasystems** [comment]
Thanks! Unfortunately this does not fix the issue on iOS, but I'm now more or less completely convinced that's Safari's fault.
